In [1]:
import IPython
import IPython.display
import numpy as np
import pandas as pd
import glob
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import random
import sklearn as sk
from sklearn.model_selection import train_test_split
#from keras.layers import CuDNNGRU

In [2]:
labels_df = pd.read_csv("D:\Clases\Tesis\Datasets\Gaia\GAIA_dataset.dat")
labels_df = labels_df[labels_df['N'] >= 24]

In [3]:
path = "D:\Clases\Tesis\Datasets\Gaia\LCs\\"
frames = []
j = 0
for index, row in labels_df.iterrows():
    filename = path + str(row['ID']) + ".dat"
    j = j+1
    if j%1 == 0:
        print(j)
        #frame = pd.read_csv(filename, index_col=None, header=None, sep= ',', error_bad_lines=False, skipinitialspace=True)
        frame = pd.read_csv(filename, header=0)
        lower_bound = 11
        upper_bound = lower_bound+5
        #print('File: ' + filename)
        serie = frame.iloc[1:24,0:2]
        #print(serie)
        patch = frame.iloc[lower_bound:upper_bound, 0:2]
        temp_patch = frame.iloc[lower_bound:upper_bound+1, 0:2]
        #print(patch)
        min_serie = serie.iloc[:,1]
        min_value = min(min_serie) - 2
        patch_min = np.full((5, 2), min_value)
        #print(patch_min)
        patch_min[:,0] = patch.iloc[:,0]
        temp_newframe = np.concatenate((frame.iloc[1:lower_bound, 0:2], patch_min, frame.iloc[upper_bound:23, 0:2], temp_patch))
        newframe_diff = np.diff(temp_newframe, axis = 0)
        temp_newframe = pd.DataFrame(temp_newframe)  
        temp_newframe = temp_newframe.iloc[0:27, 0:2]   
        newframe_diff = pd.DataFrame(newframe_diff)
        newframe = np.concatenate((temp_newframe, newframe_diff), axis = 1)
        frames.append(newframe)
        print(newframe)

1
[[ 1.71130843e+03  1.97558993e+01  2.18716168e+01  1.62956690e-01]
 [ 1.73318005e+03  1.99188560e+01  1.76145710e-01 -6.15443670e-01]
 [ 1.73335619e+03  1.93034123e+01  2.50145300e-01  5.67699680e-01]
 [ 1.73360634e+03  1.98711120e+01  2.50142620e-01 -4.26121000e-01]
 [ 1.73385648e+03  1.94449910e+01  5.00268309e+00  4.79982870e-01]
 [ 1.73885916e+03  1.99249739e+01  2.50144280e-01 -2.50725770e-01]
 [ 1.73910931e+03  1.96742481e+01  7.40015000e-02  1.84989440e-01]
 [ 1.73918331e+03  1.98592375e+01  1.76145300e-01  1.66250580e-01]
 [ 1.73935945e+03  2.00254881e+01  7.39741300e-02 -1.04037160e+00]
 [ 1.73943343e+03  1.89851165e+01  1.76175350e-01 -2.00000000e+00]
 [ 1.73960960e+03  1.69851165e+01  8.73677722e+01  0.00000000e+00]
 [ 1.82697738e+03  1.69851165e+01  1.76171190e-01  0.00000000e+00]
 [ 1.82715355e+03  1.69851165e+01  7.40049600e-02  0.00000000e+00]
 [ 1.82722755e+03  1.69851165e+01  1.76174880e-01  0.00000000e+00]
 [ 1.82740373e+03  1.69851165e+01  1.05058627e+01  2.1243601

 [ 2.02515726e+03  1.38256019e+01  7.40027700e-02  5.21660000e-04]]
10
[[ 1.73292866e+03  1.89867342e+01  1.76145680e-01  4.00153630e-01]
 [ 1.73310480e+03  1.93868878e+01  7.40016500e-02  1.17407000e-01]
 [ 1.73317881e+03  1.95042948e+01  1.76143730e-01  1.49768380e-01]
 [ 1.73335495e+03  1.96540632e+01  5.00271319e+00 -3.52989360e-01]
 [ 1.73835766e+03  1.93010738e+01  7.40009800e-02  1.76139800e-01]
 [ 1.73843166e+03  1.94772136e+01  1.76115950e-01  3.26909100e-02]
 [ 1.73860778e+03  1.95099045e+01  7.40298400e-02  7.02729800e-02]
 [ 1.73868181e+03  1.95801775e+01  1.76145840e-01 -4.61893380e-01]
 [ 1.73885795e+03  1.91182841e+01  7.40025000e-02  1.16548450e-01]
 [ 1.73893196e+03  1.92348326e+01  2.50151050e-01 -2.24809841e+00]
 [ 1.73918211e+03  1.69867342e+01  8.80465976e+01  0.00000000e+00]
 [ 1.82722871e+03  1.69867342e+01  1.76192570e-01  0.00000000e+00]
 [ 1.82740490e+03  1.69867342e+01  7.40121000e-02  0.00000000e+00]
 [ 1.82747891e+03  1.69867342e+01  1.76167940e-01  0.00000

 [ 2.21980411e+03  1.45982212e+01  1.76169830e-01 -5.21158000e-03]]
20
[[ 1.74280117e+03  1.60119424e+01  7.40045100e-02 -4.22410000e-04]
 [ 1.74287517e+03  1.60115200e+01  3.29053295e+01 -3.16894500e-02]
 [ 1.77578050e+03  1.59798306e+01  7.40039900e-02 -6.21945000e-03]
 [ 1.77585451e+03  1.59736111e+01  2.44181262e+01  1.11964190e-01]
 [ 1.80027263e+03  1.60855753e+01  7.40324900e-02  7.27677000e-03]
 [ 1.80034667e+03  1.60928521e+01  3.77039779e+01  4.10456270e-01]
 [ 1.83805065e+03  1.65033083e+01  1.74267306e+01  2.34038360e-01]
 [ 1.85547738e+03  1.67373467e+01  7.40350700e-02  2.68159900e-02]
 [ 1.85555141e+03  1.67641627e+01  3.91997251e+01  4.69165150e-01]
 [ 1.89475114e+03  1.72333278e+01  2.12484702e+01 -3.45514154e+00]
 [ 1.91599961e+03  1.37781863e+01  3.62216040e+01  0.00000000e+00]
 [ 1.95222121e+03  1.37781863e+01  3.24145446e+01  0.00000000e+00]
 [ 1.98463575e+03  1.37781863e+01  7.40376300e-02  0.00000000e+00]
 [ 1.98470979e+03  1.37781863e+01  3.04959367e+01  0.00000

KeyboardInterrupt: 

In [4]:
df = pd.DataFrame(np.row_stack(frames))
df

0          1          2         3
0        1711.308429  19.755899  21.871617  0.162957
1        1733.180046  19.918856   0.176146 -0.615444
2        1733.356191  19.303412   0.250145  0.567700
3        1733.606337  19.871112   0.250143 -0.426121
4        1733.856479  19.444991   5.002683  0.479983
...              ...        ...        ...       ...
4527490  1897.207489  15.300551   0.176172 -0.545437
4527491  1897.383662  14.755114   0.073992  0.170549
4527492  1897.457654  14.925663   0.176193  0.260562
4527493  1897.633847  15.186224   0.074013  0.052815
4527494  1897.707861  15.239039   0.176172  0.113632

[4527495 rows x 4 columns]

In [5]:
df.to_hdf('gaia_data2vec_full_4features.hdf', key='gaia_data2vec_full_4features')